
export const users = [
    {
        'id':1,
        'firstName':'Edison',
        'lastName':'Qerimi',
        'username':'eddqerimi',
        'email':'edisonqerimii1@gmail.com',
        'password':'password',
        'role':'admin'
    },
    {
        'id':2,
        'firstName':'Will',
        'lastName':'Smith',
        'username':'willsmith',
        'email':'willsmith@gmail.com',
        'password':'willsmith',
        'role':'',
    },
    {
        'id':3,
        'firstName':'Denzel',
        'lastName':'Washington',
        'username':'dwashington',
        'email':'denzelwashington@gmail.com',
        'password':'denzel123',
        'role':'',
    }
]
